services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb:1337
    restart: always
    volumes:
      - dbvolume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5000000
    networks:
      - wp_bridge
    env_file:
      - .env
  
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress:1337
    restart: always
    volumes:
      - wpvolume:/var/www/html
    networks:
      - wp_bridge
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:1337
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wpvolume:/var/www/html
    networks:
      - wp_bridge
    depends_on:
      - wordpress

volumes:
  dbvolume:
    name: dbvolume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mabahani/data/DB
  wpvolume:
    name: wpvolume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mabahani/data/WordPress

networks:
  wp_bridge:
    name: wp_bridge
    driver: bridge