services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb:1337
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - wp_bridge
    env_file:
      - /home/mabahani/Desktop/test/.env
  
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress:1337
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wpvolume:/var/www/html
    networks:
      - wp_bridge
    depends_on:
      - mariadb
    env_file:
      - /home/mabahani/Desktop/test/.env

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1337
    restart: always
    ports:
      - 443:443
    volumes:
      - wpvolume:/var/www/html
    networks:
      - wp_bridge
    depends_on:
      - wordpress

volumes:
  dbvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mabahani/data/DB
  wpvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mabahani/data/WordPress

networks:
  wp_bridge:
    driver: bridge