services:
  mariadb:
    image: ./mariadb
    container_name: marianame
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - wp_bridge
  
  wordpress:
    image: ./wordpress
    container_name: wpanem
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wpvolume:/var/www/html
    networks:
      - wp_bridge
    depends_on:
      - mariadb

  nginx:
    image: ./nginx
    container_name: nginxname
    restart: always
    ports:
      - 443:443
    volumes:
      - wpvolume:/var/www/html
    networks:
      - wp_bridge
    depends_on:
      - wordpress

volumes:
  dbvolume:
    - driver: local
    - driver_opts:
        type: none
        o: bind
        device: /home/username/mariadb
  wpvolume: